import FeaturesTwo from "@/components/Home/FeaturesTwo";
import HomeFooter from "@/components/Home/HomeFooter";
import { Box, Container } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Features from "src/components/Home/Features";
import HomeHeader from "../components/Home/HomeHeader";
import HomeHero from "../components/Home/HomeHero";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  const [isBusiness, setIsBusiness] = useState(false);

  return (
    <Box h="full" w="full">
      <Head>
        <title>TaxitPay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box h="100vh" bg="#060809">
        <Container maxW="container.xl" className={styles.container}>
          <HomeHeader setBusiness={(val) => setIsBusiness(val)} isBusiness={isBusiness} />
          <HomeHero isBusiness={isBusiness} />
        </Container>
      </Box>

      <Box as="main" zIndex={999} bg="white" border={["none", "5px solid white"]}>
        <Features isBusiness={isBusiness} />
        <FeaturesTwo isBusiness={isBusiness} />
      </Box>

      <Box as="footer" mt={["32"]}>
        <HomeFooter />
      </Box>
    </Box>
  );
};

export default Home;
